import { NgModule, ErrorHandler } from '@angular/core';
import { NotFoundComponent } from './not-found/not-found.component';
import { RouterModule } from '@angular/router';
import { HeaderComponent } from './header/header.component';
import { FooterComponent } from './footer/footer.component';
import { ActionBarComponent } from './action-bar/action-bar.component';
import { HttpClientModule } from '@angular/common/http';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TokenService } from './services/token.service';
import { ApplicationStateService } from './services/application-state.service';
import { SideNavComponent } from './side-nav/side-nav.component';
import { ChangePasswordModalComponent } from './change-password/change-password-modal.component';
import { GenericErrorHandler } from './services/generic-error.handler';
import { NgxMasonryModule } from 'ngx-masonry';
import { ImageService } from './services/image.service';
import { SocketIoConfig, SocketIoModule } from 'ngx-socket-io';
import { environment } from '../../environments/environment';
import { LoadingComponent } from './loading/loading.component';

import {
  NzAvatarModule,
  NzBadgeModule,
  NzButtonModule,
  NzCardModule,
  NzCheckboxModule,
  NzCommentModule,
  NzDatePickerModule,
  NzDescriptionsModule,
  NzFormModule,
  NzIconModule,
  NzInputModule,
  NzLayoutModule,
  NzListModule,
  NzMenuModule,
  NzModalModule,
  NzNotificationModule,
  NzPopoverModule,
  NzResultModule,
  NzSelectModule,
  NzSkeletonModule,
  NzTabsModule,
  NzTagModule,
  NzTimePickerModule,
  NzToolTipModule,
  NzUploadModule,
  NzAffixModule,
  NzAlertModule,
  NzAnchorModule,
  NzAutocompleteModule,
  NzBackTopModule,
  NzBreadCrumbModule,
  NzCalendarModule,
  NzCarouselModule,
  NzCascaderModule,
  NzCollapseModule,
  NzDividerModule,
  NzDrawerModule,
  NzDropDownModule,
  NzEmptyModule,
  NzGridModule,
  NzI18nModule,
  NzInputNumberModule,
  NzMentionModule,
  NzMessageModule,
  NzNoAnimationModule,
  NzPageHeaderModule,
  NzPaginationModule,
  NzPopconfirmModule,
  NzProgressModule,
  NzRadioModule,
  NzRateModule,
  NzSliderModule,
  NzSpinModule,
  NzStatisticModule,
  NzStepsModule,
  NzSwitchModule,
  NzTableModule,
  NzTimelineModule,
  NzTransButtonModule,
  NzTransferModule,
  NzTreeModule,
  NzTreeSelectModule,
  NzTypographyModule,
  NzWaveModule,
} from 'ng-zorro-antd';
import { NzResizableModule } from 'ng-zorro-antd/resizable';

const socketConfig: SocketIoConfig = { url: `${environment.BASEURL}`, options: {} };
const zorroModules = [
  NzAffixModule,
  NzAlertModule,
  NzAnchorModule,
  NzAutocompleteModule,
  NzAvatarModule,
  NzBackTopModule,
  NzBadgeModule,
  NzButtonModule,
  NzBreadCrumbModule,
  NzCalendarModule,
  NzCardModule,
  NzCarouselModule,
  NzCascaderModule,
  NzCheckboxModule,
  NzCollapseModule,
  NzCommentModule,
  NzDatePickerModule,
  NzDescriptionsModule,
  NzDividerModule,
  NzDrawerModule,
  NzDropDownModule,
  NzEmptyModule,
  NzFormModule,
  NzGridModule,
  NzI18nModule,
  NzIconModule,
  NzInputModule,
  NzInputNumberModule,
  NzLayoutModule,
  NzListModule,
  NzMentionModule,
  NzMenuModule,
  NzMessageModule,
  NzModalModule,
  NzNoAnimationModule,
  NzNotificationModule,
  NzPageHeaderModule,
  NzPaginationModule,
  NzPopconfirmModule,
  NzPopoverModule,
  NzProgressModule,
  NzRadioModule,
  NzRateModule,
  NzResultModule,
  NzSelectModule,
  NzSkeletonModule,
  NzSliderModule,
  NzSpinModule,
  NzStatisticModule,
  NzStepsModule,
  NzSwitchModule,
  NzTableModule,
  NzTabsModule,
  NzTagModule,
  NzTimePickerModule,
  NzTimelineModule,
  NzToolTipModule,
  NzTransButtonModule,
  NzTransferModule,
  NzTreeModule,
  NzTreeSelectModule,
  NzTypographyModule,
  NzUploadModule,
  NzWaveModule,
  NzResizableModule,
];

@NgModule({
  declarations: [
    NotFoundComponent,
    HeaderComponent,
    FooterComponent,
    ActionBarComponent,
    SideNavComponent,
    ChangePasswordModalComponent,
    LoadingComponent,
  ],
  imports: [
    zorroModules,
    RouterModule,
    HttpClientModule,
    FormsModule,
    ReactiveFormsModule,
    NgxMasonryModule,
    SocketIoModule.forRoot(socketConfig),
  ],
  exports: [
    zorroModules,
    SocketIoModule,
    HttpClientModule,
    FormsModule,
    ReactiveFormsModule,
    NgxMasonryModule,
    HeaderComponent,
    FooterComponent,
    ActionBarComponent,
    SideNavComponent,
    ChangePasswordModalComponent,
    LoadingComponent,
  ],
  providers: [
    ImageService,
    TokenService,
    ApplicationStateService,
    { provide: ErrorHandler, useClass: GenericErrorHandler },
  ]
})
export class SharedModule { }
